# @package _global_
defaults:
  - /lte_img_not_base
  - _self_

task:
  name: lh_aloha_image
  lte_temporal_rgb_key: top
  lte_horizon: 16
  lte_n_obs_steps: 2
  lte_n_action_steps: 8
  shape_meta:
    obs:
      top: {shape: [3, 84, 84], type: rgb}
      right_wrist: {shape: [3, 84, 84], type: rgb}
      qpos: {shape: [7]}
    action: {shape: [7]}
  dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
    dataset_path: data/aloha_twomodes_single/demos.hdf5
    shape_meta: ${task.shape_meta}
    horizon: ${horizon}
    n_obs_steps: ${dataset_obs_steps}
    subsample_frames: 1
    pad_before: 16
    pad_after: 16
    abs_action: false
    rotation_rep: rotation_6d
    use_legacy_normalizer: false
    use_cache: false
    cache_images_in_memory: true
    seed: 42
    val_ratio: 0.02
    return_temporal_history: true
  env_runner:
    _target_: diffusion_policy.env_runner.aloha_image_runner.AlohaImageRunner
    dataset_path: ${task.dataset.dataset_path}
    shape_meta: ${task.shape_meta}
    task_name: sim_singlearm_pickandplace_twomodes_scripted
    n_train: 0
    n_train_vis: 0
    train_start_idx: 0
    n_test: 5
    n_test_vis: 2
    test_start_seed: 100000
    max_steps: 500
    n_obs_steps: ${n_obs_steps}
    n_action_steps: ${n_action_steps}
    subsample_frames: 1
    render_obs_key: top
    fps: 10
    crf: 22
    past_action: false
    abs_action: false
    n_envs: 10
    tqdm_interval_sec: 1.0

# Match experiment_configs/aloha/transformer_aloha.yaml.
training:
  num_epochs: 3500
  lr_warmup_steps: 1000
  rollout_every: 100
  checkpoint_every: 50
  val_every: 1
  sample_every: 5
